services:
  pricing-db:
    image: postgres:16
    container_name: pricing-db
    environment:
      POSTGRES_DB: pricing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7429867
    ports:
      - "5435:5432"
    volumes:
      - pricing_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pricing_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  audit-db:
    image: postgres:16
    container_name: audit-db
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7429867
    ports:
      - "5436:5432"
    volumes:
      - audit_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d audit_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  pricing-app:
    build: .
    container_name: pricing-app
    depends_on:
      pricing-db:
        condition: service_healthy
      audit-db:
        condition: service_healthy
    ports:
      - "8017:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker,control,bootstrap
      PRICING_DB_USER: postgres
      PRICING_DB_PASSWORD: 7429867
      AUDIT_DB_USER: postgres
      AUDIT_DB_PASSWORD: 7429867

volumes:
  pricing_db_data:
  audit_db_data: