spring:
  config:
    activate:
      on-profile: dev

  datasource:
    pricing:
      url: jdbc:postgresql://localhost:5432/pricing_db
      username: postgres
      password: 7429867
      driver-class-name: org.postgresql.Driver

    audit:
      url: jdbc:postgresql://localhost:5432/audit_db
      username: postgres
      password: 7429867
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

pricing:
  jpa:
    hibernate:
      ddl-auto: update

audit:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    com.kratos: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

ledger:
  accounts:
    cantonment: "ACC-CANT"
    exploitation: "ACC-EXP"
    tax: "ACC-TAX"
    taxRate: "ACC-TAX-RATE"
    taxFixed: "ACC-TAX-FIXED"
    external: "ACC-EXT"
    distributed: "ACC-DIST"
    distributedSuperDistributor: "ACC-DIST-SUPER-DISTRIBUTOR"
    distributedDistributor: "ACC-DIST-DISTRIBUTOR"
    distributedAgent: "ACC-DIST-AGENT"
    currency: "XAF"
    bankClearing: "ACC-BANK-CLEAR"

mok:
  currency:
    default: "XAF"



