spring:
  config:
    activate:
      on-profile: dev

  datasource:
    pricing:
      url: jdbc:postgresql://localhost:5432/pricing_db
      username: postgres
      password: 7429867
      driver-class-name: org.postgresql.Driver

    audit:
      url: jdbc:postgresql://localhost:5432/audit_db
      username: postgres
      password: 7429867
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

pricing:
  jpa:
    hibernate:
      ddl-auto: update

audit:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
