spring:
  config:
    activate:
      on-profile: docker

  datasource:
    pricing:
      url: jdbc:postgresql://pricing-db:5432/pricing_db
      username: ${PRICING_DB_USER:postgres}
      password: ${PRICING_DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

    audit:
      url: jdbc:postgresql://audit-db:5432/audit_db
      username: ${AUDIT_DB_USER:postgres}
      password: ${AUDIT_DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

pricing:
  jpa:
    hibernate:
      ddl-auto: update

audit:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

external:
  accounts:
    base-url: "https://accounts.mok.internal"

ledger:
  accounts:
    cantonment: "ACC-CANT"
    exploitation: "ACC-EXP"
    tax: "ACC-TAX"
    taxRate: "ACC-TAX-RATE"
    taxFixed: "ACC-TAX-FIXED"
    external: "EXTERNAL_ACCOUNT"
    distributed: "ACC-DIST"
    distributedSuperDistributor: "ACC-DIST-SUPER-DISTRIBUTOR"
    distributedDistributor: "ACC-DIST-DISTRIBUTOR"
    distributedAgent: "ACC-DIST-AGENT"
    distributedTaxRate: "ACC-DIST-TAX-RATE"
    currency: "XAF"
    bankClearing: "ACC-BANK-CLEAR"
    fees: "FEES_ACCOUNT"

mok:
  currency:
    default: "XAF"