spring:
  application:
    name: mok-pricing-engine

  jackson:
    serialization:
      INDENT_OUTPUT: false
  config:
    import: "classpath:bootstrap/pricing-defaults.yml"
  jpa:
    open-in-view: false

server:
  servlet:
    context-path: /api
