spring:
  config:
    activate:
      on-profile: docker

  datasource:
    pricing:
      url: jdbc:postgresql://pricing-db:5432/pricing_db
      username: ${PRICING_DB_USER:postgres}
      password: ${PRICING_DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

    audit:
      url: jdbc:postgresql://audit-db:5432/audit_db
      username: ${AUDIT_DB_USER:postgres}
      password: ${AUDIT_DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

pricing:
  jpa:
    hibernate:
      ddl-auto: update

audit:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

ledger:
  accounts:
    cantonment: ${LEDGER_CANT:ACC-CANT}
    exploitation: ${LEDGER_EXP:ACC-EXP}
    tax: ${LEDGER_TAX:ACC-TAX}
    taxRate: ${ACC-TAX-RATE:ACC-TAX-RATE}
    taxFixed: ${ACC-TAX-FIXED:ACC-TAX-FIXED}
    external: ${ACC-EXT:ACC-EXT}
    distributed: ${ACC-DIST:ACC-DIST}
    currency: "XAF"
    bankClearing: ${ACC-BANK-CLEAR:ACC-BANK-CLEAR}

mok:
  currency:
    default: "XAF"

